language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-27.0.1
    - android-26
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

before_script:
  - echo yes | android update sdk --no-ui --all --filter platform-tools,tools
  - echo yes | android update sdk --no-ui --all --filter build-tools-27.0.1
  - echo yes | android update sdk --no-ui --all --filter android-26

script:
    - ./gradlew clean test
